import { createClient } from '@supabase/supabase-js'
import { apiUrl, appConfig } from '../shared/utils/config.js'
import { auth } from '../shared/utils/auth.js'
import { apiFetch as sharedApiFetch } from '../shared/utils/api.js'
import { supabase as sharedSupabase } from '../shared/utils/supabase.js'
import { escapeHTML } from './format.js'

// Store iframe URLs generated by search.
export const currentIframeUrls = window.currentIframeUrls = {
  noapc: "",
  resurchify: "",
  wos: ""
}

// Embedded lookup data is loaded from /tapchi/embedded-data.js before this module.
export const hdgsnnData = window.hdgsnnData || []
export const pdfData = window.pdfData || []

if (!sharedSupabase) {
  throw new Error('Missing Supabase configuration. Create .env from .env.example.')
}

export const db = sharedSupabase
export const publicDb = createClient(
  appConfig.SUPABASE_URL,
  appConfig.SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storageKey: 'lelong-public-readonly',
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false
    }
  }
)

const initialAuthUrl = new URL(location.href)
const initialAuthHash = new URLSearchParams(initialAuthUrl.hash.slice(1))
const initialPasswordRecovery = initialAuthUrl.searchParams.get('recovery') === '1'
  || initialAuthUrl.searchParams.get('type') === 'recovery'
  || initialAuthHash.get('type') === 'recovery'
    let currentSession = null;
    let currentAccount = null;
    let currentAuthMode = 'login';
    let accountRefreshPromise = null;
    let accountRealtimeChannel = null;
    let accountRealtimeUserId = null;
    let accountRealtimeTimer = null;
    let adminRealtimeChannel = null;
    let adminRealtimeTimer = null;
    let adminRealtimeFallbackTimer = null;
    let paymentPollTimer = null;
    let activePaymentCode = null;
    let passwordRecoveryActive = false;
    let passwordRecoveryRequested = initialPasswordRecovery;
    let configuredTrialDays = 30;
    let publicConfigPromise = null;

    function loadPublicConfig() {
      if (publicConfigPromise) return publicConfigPromise;
      publicConfigPromise = fetch(apiUrl('/api/public/config'))
        .then(response => response.ok ? response.json() : Promise.reject(new Error('Không tải được cấu hình')))
        .then(config => {
          configuredTrialDays = Number(config.trial_days || 30);
          return configuredTrialDays;
        })
        .catch(() => configuredTrialDays);
      return publicConfigPromise;
    }

    function setUserMessage(message = '', type = '') {
      const element = document.getElementById('authMessage');
      if (!element) return;
      element.textContent = message;
      element.className = `vip-message ${type}`.trim();
    }

    function hasLocalAuthForm() {
      return Boolean(document.getElementById('authView') && document.getElementById('authForm'));
    }

    function redirectToSharedAuth(mode = 'login') {
      const target = new URL('/', location.origin);
      if (mode === 'reset' || passwordRecoveryRequested) {
        target.search = location.search;
        target.hash = location.hash;
        if (!target.searchParams.has('recovery') && !target.searchParams.has('type')) {
          target.searchParams.set('recovery', '1');
        }
      } else {
        target.hash = mode === 'register' ? 'register' : 'login';
      }
      window.location.href = target.toString();
    }

    function setAuthMode(mode) {
      if (!hasLocalAuthForm()) {
        redirectToSharedAuth(mode);
        return;
      }
      currentAuthMode = mode;
      const registering = mode === 'register';
      document.getElementById('loginTab').classList.toggle('active', !registering);
      document.getElementById('registerTab').classList.toggle('active', registering);
      document.getElementById('authNameField').style.display = registering ? 'grid' : 'none';
      document.getElementById('authName').required = registering;
      document.getElementById('authPassword').autocomplete = registering ? 'new-password' : 'current-password';
      document.getElementById('authHeading').textContent = registering ? 'Tạo tài khoản mới' : 'Chào mừng trở lại';
      document.getElementById('authLead').textContent = registering
        ? `Đăng ký để nhận ${configuredTrialDays} ngày dùng thử miễn phí và bắt đầu trò chuyện cùng AI.`
        : 'Đăng nhập để tiếp tục sử dụng Trợ lý Tạp chí AI.';
      document.getElementById('authSubmitLabel').textContent = registering ? 'Tạo tài khoản' : 'Đăng nhập';
      document.getElementById('authWelcome').style.display = 'block';
      document.getElementById('authTabs').style.display = 'flex';
      document.getElementById('authForm').style.display = 'grid';
      document.getElementById('resetView').style.display = 'none';
      setUserMessage();
    }

    function showPasswordRecovery() {
      if (!hasLocalAuthForm()) {
        redirectToSharedAuth('reset');
        return;
      }
      passwordRecoveryActive = true;
      document.getElementById('userModal').classList.add('open');
      document.getElementById('authView').style.display = 'block';
      document.getElementById('accountView').style.display = 'none';
      document.getElementById('paymentBox').classList.remove('open');
      document.getElementById('paymentQr').removeAttribute('src');
      document.getElementById('authWelcome').style.display = 'none';
      document.getElementById('authTabs').style.display = 'none';
      document.getElementById('authForm').style.display = 'none';
      document.getElementById('resetView').style.display = 'grid';
      setUserMessage('Liên kết hợp lệ. Hãy tạo mật khẩu mới.', 'success');
      setTimeout(() => document.getElementById('newPassword').focus(), 0);
    }

    function togglePasswordVisibility(inputId, button) {
      const input = document.getElementById(inputId);
      const showing = input.type === 'text';
      input.type = showing ? 'password' : 'text';
      button.innerHTML = `<i class="fas fa-${showing ? 'eye' : 'eye-slash'}"></i>`;
      button.setAttribute('aria-label', showing ? 'Hiện mật khẩu' : 'Ẩn mật khẩu');
    }

    async function openUserModal(forceModal = false) {
      if (currentSession && !forceModal && !passwordRecoveryActive && !passwordRecoveryRequested) {
        await openAccountPortal();
        return;
      }
      if (!currentSession && !hasLocalAuthForm()) {
        redirectToSharedAuth('login');
        return;
      }
      document.getElementById('userModal').classList.add('open');
      const recovering = passwordRecoveryActive || passwordRecoveryRequested;
      const authView = document.getElementById('authView');
      const accountView = document.getElementById('accountView');
      if (authView) authView.style.display = recovering || !currentSession ? 'block' : 'none';
      if (accountView) accountView.style.display = currentSession && !recovering ? 'block' : 'none';
      if (currentSession && !currentAccount) void refreshAccount();
    }

    function closeUserModal() {
      document.getElementById('userModal').classList.remove('open');
      void cancelPendingPayment();
    }

    async function submitAuth(event) {
      event.preventDefault();
      const email = document.getElementById('authEmail').value.trim();
      const password = document.getElementById('authPassword').value;
      const displayName = document.getElementById('authName').value.trim();
      const submit = document.getElementById('authSubmit');
      submit.disabled = true;
      setUserMessage('Đang xử lý...');
      try {
        if (currentAuthMode === 'register') {
          const { session, error } = await auth.signUp(email, password, { display_name: displayName }, { emailRedirectTo: `${location.origin}${location.pathname}` });
          if (error) throw error;
          if (!session) {
            setUserMessage('Đăng ký thành công. Hãy kiểm tra email để xác minh tài khoản.', 'success');
          } else {
            closeUserModal();
          }
        } else {
          const { error } = await auth.signIn(email, password);
          if (error) throw error;
          closeUserModal();
        }
      } catch (error) {
        setUserMessage(error.message || 'Không thể xác thực tài khoản.', 'error');
      } finally {
        submit.disabled = false;
      }
    }

    async function requestPasswordReset() {
      const email = document.getElementById('authEmail').value.trim();
      if (!email) {
        setUserMessage('Nhập email trước khi yêu cầu đặt lại mật khẩu.', 'error');
        document.getElementById('authEmail').focus();
        return;
      }
      const button = document.getElementById('passwordResetRequest');
      button.disabled = true;
      button.textContent = 'Đang gửi...';
      const redirectUrl = new URL(location.href);
      redirectUrl.search = '';
      redirectUrl.hash = '';
      redirectUrl.searchParams.set('recovery', '1');
      try {
        const { error } = await auth.resetPassword(email, redirectUrl.toString());
        if (error) throw error;
        setUserMessage('Đã gửi liên kết đặt lại mật khẩu. Vui lòng kiểm tra hộp thư và thư rác.', 'success');
      } catch (error) {
        setUserMessage(error.message || 'Không thể gửi email đặt lại mật khẩu.', 'error');
      } finally {
        button.disabled = false;
        button.textContent = 'Quên mật khẩu?';
      }
    }

    function passwordRuleState(password) {
      return {
        length: password.length >= 8,
        lower: /[a-z]/.test(password),
        upper: /[A-Z]/.test(password),
        number: /[0-9]/.test(password),
        special: /[^A-Za-z0-9\s]/.test(password)
      };
    }

    function updatePasswordRules(password) {
      const rules = passwordRuleState(password);
      document.querySelectorAll('#passwordRules .password-rule').forEach(element => {
        const valid = Boolean(rules[element.dataset.rule]);
        element.classList.toggle('valid', valid);
        element.querySelector('i').className = valid ? 'fas fa-circle-check' : 'fas fa-circle';
      });
      return Object.values(rules).every(Boolean);
    }

    async function ensurePasswordRecoverySession() {
      const session = await auth.getSession();
      const sessionData = { session };
      if (sessionData.session) return sessionData.session;

      const accessToken = initialAuthHash.get('access_token');
      const refreshToken = initialAuthHash.get('refresh_token');
      if (accessToken && refreshToken) {
        const { data, error } = await db.auth.setSession({
          access_token: accessToken,
          refresh_token: refreshToken
        });
        if (!error && data.session) return data.session;
      }

      const code = initialAuthUrl.searchParams.get('code');
      if (code) {
        const { data, error } = await db.auth.exchangeCodeForSession(code);
        if (!error && data.session) return data.session;
      }
      throw new Error('Liên kết đặt lại mật khẩu đã hết hạn hoặc đã được sử dụng. Hãy yêu cầu liên kết mới.');
    }

    async function saveNewPassword(event) {
      event.preventDefault();
      const password = document.getElementById('newPassword').value;
      const confirmation = document.getElementById('confirmNewPassword').value;
      const button = document.getElementById('saveNewPasswordButton');
      if (!updatePasswordRules(password)) {
        setUserMessage('Mật khẩu chưa đáp ứng đầy đủ các điều kiện bảo mật.', 'error');
        return;
      }
      if (password !== confirmation) {
        setUserMessage('Hai mật khẩu chưa trùng khớp.', 'error');
        return;
      }
      button.disabled = true;
      button.innerHTML = '<i class="fas fa-circle-notch fa-spin"></i>&nbsp; Đang cập nhật...';
      try {
        await ensurePasswordRecoverySession();
        const { error } = await auth.updatePassword(password);
        if (error) throw error;
        passwordRecoveryActive = false;
        passwordRecoveryRequested = false;
        document.getElementById('resetView').reset();
        updatePasswordRules('');
        await auth.signOut();
        currentSession = null;
        currentAccount = null;
        const cleanUrl = new URL(location.href);
        cleanUrl.searchParams.delete('recovery');
        cleanUrl.searchParams.delete('code');
        cleanUrl.hash = '';
        history.replaceState({}, '', `${cleanUrl.pathname}${cleanUrl.search}`);
        setAuthMode('login');
        document.getElementById('authView').style.display = 'block';
        document.getElementById('accountView').style.display = 'none';
        document.getElementById('userModal').classList.add('open');
        setUserMessage('Đổi mật khẩu thành công. Hãy đăng nhập bằng mật khẩu mới.', 'success');
      } catch (error) {
        const message = /auth session missing/i.test(error.message || '')
          ? 'Liên kết đặt lại mật khẩu đã hết hạn hoặc đã được sử dụng. Hãy yêu cầu liên kết mới.'
          : error.message;
        setUserMessage(message || 'Không thể cập nhật mật khẩu.', 'error');
      } finally {
        button.disabled = false;
        button.innerHTML = '<i class="fas fa-floppy-disk"></i>&nbsp; Lưu mật khẩu mới';
      }
    }

    async function signOutUser() {
      await cancelPendingPayment();
      resetRealtimeSubscriptions();
      await auth.signOut();
      currentAccount = null;
      closeAccountPortal();
      closeUserModal();
    }

    async function apiFetch(path, options = {}) {
      const session = await auth.getSession();
      if (!session?.access_token) throw new Error('Bạn cần đăng nhập.');
      currentSession = session;
      return sharedApiFetch(path, options);
    }
    async function cancelPendingPayment() {
      const code = activePaymentCode;
      if (!code) return;

      activePaymentCode = null;
      stopPaymentPolling();
      document.getElementById('paymentBox').classList.remove('open');
      document.getElementById('paymentQr').removeAttribute('src');
      try {
        await apiFetch(`/api/orders/${encodeURIComponent(code)}`, { method: 'DELETE' });
        if (currentAccount?.payments) {
          currentAccount.payments = currentAccount.payments.filter(payment => payment.payment_code !== code);
          renderPortalTables();
        }
      } catch (error) {
        console.warn('Không thể hủy đơn thanh toán đang chờ:', error.message);
      }
    }

    function renderAccount(account) {
      if (!account) return;
      document.getElementById('accountEmail').textContent = account.user.email || '';
      const status = document.getElementById('vipStatus');
      const trialDays = Number(account.subscription?.vip_plans?.trial_days || 30);
      const isAdmin = account.role === 'admin' || isAdminAccount(account);
      status.textContent = isAdmin
        ? 'VIP Vĩnh viễn (Admin)'
        : account.is_trial
          ? `Đang dùng thử miễn phí ${trialDays} ngày`
          : getRemainingCredits(account) > 0 ? 'VIP đang hoạt động' : 'Đã hết lượt VIP';
      status.className = account.is_vip ? 'vip-active' : 'vip-inactive';
      const expiryRow = document.getElementById('vipExpiryRow');
      const expiry = account.is_trial ? account.subscription?.trial_ends_at : null;
      expiryRow.style.display = expiry && !isAdmin ? 'flex' : 'none';
      if (expiry && !isAdmin) document.getElementById('vipExpiry').textContent = new Date(expiry).toLocaleDateString('vi-VN');
      const limit = account.subscription?.vip_plans?.daily_ai_limit || 30;
      document.getElementById('vipUsage').textContent = isAdmin ? 'Vô hạn' : account.is_trial ? `${account.usage_today || 0}/${limit} hôm nay` : `${getRemainingCredits(account)} lượt`;
      document.getElementById('vipWalletBalance').textContent = isAdmin ? 'Vô hạn' : formatVnd(getWalletBalance(account));
      const chatAccessNote = document.getElementById('chat-access-note');
      if (chatAccessNote) chatAccessNote.style.display = account.is_vip ? 'none' : 'block';
      renderPortalAccount(account);
    }

    let adminDashboardData = null;
    let userChartMode = 'week';
    let adminChartMode = 'day';
    let portalHistoryPushed = false;
    const portalPageAliases = {
      dashboard: { admin: 'adminDashboard', client: 'userOverview' },
      invoices: { admin: 'adminInvoices', client: 'userTransactions' },
      payments: { admin: 'adminInvoices', client: 'userTransactions' },
      users: { admin: 'adminUsers', client: 'userOverview' },
      settings: { admin: 'adminSettings', client: 'userOverview' },
      userOverview: { admin: 'adminDashboard', client: 'userOverview' },
      userTransactions: { admin: 'adminInvoices', client: 'userTransactions' },
      adminDashboard: { admin: 'adminDashboard', client: 'userOverview' },
      adminInvoices: { admin: 'adminInvoices', client: 'userTransactions' },
      adminUsers: { admin: 'adminUsers', client: 'userOverview' },
      adminSettings: { admin: 'adminSettings', client: 'userOverview' }
    };

    function isAdminAccount(account = currentAccount) {
      const accountUser = account?.user || currentAccount?.user || {};
      const sessionUser = currentSession?.user || {};
      const role = sessionUser.app_metadata?.role
        || sessionUser.user_metadata?.role
        || accountUser.app_metadata?.role
        || accountUser.user_metadata?.role
        || account?.role
        || currentAccount?.role;
      return role === 'admin' || account?.role === 'admin' || currentAccount?.role === 'admin';
    }

    function formatPortalDate(value, fallback = 'Chưa kích hoạt') {
      if (!value) return fallback;
      const date = new Date(value);
      return Number.isNaN(date.getTime()) ? fallback : date.toLocaleDateString('vi-VN');
    }

    function formatVnd(value) {
      return `${Number(value || 0).toLocaleString('vi-VN')} đ`;
    }

    function getRemainingCredits(account) {
      const value = account?.remaining_credits ?? account?.subscription?.ai_credits_remaining;
      return Number.isFinite(Number(value)) ? Math.max(0, Number(value)) : 0;
    }

    function getWalletBalance(account) {
      const value = account?.wallet_balance_vnd ?? account?.subscription?.wallet_balance_vnd;
      return Number.isFinite(Number(value)) ? Math.max(0, Number(value)) : 0;
    }

    function renderPortalAccount(account) {
      const user = account?.user || currentSession?.user || {};
      const sessionUser = currentSession?.user || {};
      const name = sessionUser.user_metadata?.display_name || user.user_metadata?.display_name || user.email?.split('@')[0] || 'Người dùng';
      const firstLetter = name.trim().charAt(0).toUpperCase() || 'U';
      const admin = isAdminAccount(account);
      const paidPayments = (account?.payments || []).filter(payment => payment.status === 'paid');
      const start = account?.is_trial
        ? account?.subscription?.trial_started_at
        : paidPayments[paidPayments.length - 1]?.paid_at;
      const limit = account?.subscription?.vip_plans?.daily_ai_limit || 30;
      const trialDays = Number(account?.subscription?.vip_plans?.trial_days || 30);
      const used = Number(account?.usage_today || 0);
      const remainingCredits = getRemainingCredits(account);
      const walletBalance = getWalletBalance(account);
      const lastPaidCredits = Number(paidPayments.find(payment => Number(payment.credits_granted || 0) > 0)?.credits_granted
        || account?.subscription?.vip_plans?.ai_credit_amount || remainingCredits || 0);
      const creditTotal = Math.max(1, remainingCredits + Math.max(0, lastPaidCredits - remainingCredits));
      const percent = admin ? 0 : account?.is_trial
        ? Math.min(100, Math.round((used / Math.max(1, limit)) * 100))
        : Math.min(100, Math.round(((creditTotal - remainingCredits) / creditTotal) * 100));

      document.getElementById('accountPortal').classList.toggle('admin-enabled', admin);
      const overviewNav = document.getElementById('portalOverviewNav');
      if (overviewNav) {
        overviewNav.dataset.page = admin ? 'adminDashboard' : 'userOverview';
        overviewNav.dataset.portalPage = admin ? 'adminDashboard' : 'userOverview';
        overviewNav.removeAttribute('onclick');
        overviewNav.innerHTML = admin
          ? '<i class="fas fa-chart-pie"></i><span>Dashboard admin</span>'
          : '<i class="fas fa-gauge-high"></i><span>Tổng quan</span>';
      }
      const transactionNav = document.getElementById('portalTransactionsNav');
      if (transactionNav) {
        transactionNav.dataset.page = admin ? 'adminInvoices' : 'userTransactions';
        transactionNav.dataset.portalPage = admin ? 'adminInvoices' : 'userTransactions';
        transactionNav.removeAttribute('onclick');
        transactionNav.innerHTML = admin
          ? '<i class="fas fa-file-invoice-dollar"></i><span>Hóa đơn gần đây</span>'
          : '<i class="fas fa-clock-rotate-left"></i><span>Lịch sử giao dịch</span>';
      }
      const adminInvoicesNav = document.getElementById('adminInvoicesNav');
      if (adminInvoicesNav) adminInvoicesNav.style.display = admin ? 'none' : '';
      const adminDashboardNav = document.getElementById('adminDashboardNav');
      if (adminDashboardNav) adminDashboardNav.style.display = admin ? 'none' : '';
      document.getElementById('portalRoleLabel').textContent = admin ? 'Hệ thống quản trị' : 'Tài khoản người dùng';
      document.getElementById('portalProfileName').textContent = name;
      document.getElementById('portalAvatar').textContent = firstLetter;
      document.getElementById('portalVipPlan').textContent = admin
        ? 'VIP VĨNH VIỄN (ADMIN)'
        : account?.is_trial
          ? `DÙNG THỬ ${trialDays} NGÀY`
          : account?.is_vip ? String(account.subscription?.vip_plans?.name || 'PREMIUM VIP').toUpperCase()
            : 'TÀI KHOẢN STANDARD';
      document.getElementById('portalVipBadge').innerHTML = admin
        ? '<i class="fas fa-crown"></i>&nbsp; ADMIN VIP'
        : account?.is_trial
          ? '<i class="fas fa-hourglass-half"></i>&nbsp; FREE TRIAL'
          : account?.is_vip ? '<i class="fas fa-circle-check"></i>&nbsp; ACTIVE'
            : '<i class="fas fa-clock"></i>&nbsp; INACTIVE';
      document.getElementById('portalVipStart').textContent = admin ? 'Hệ thống' : formatPortalDate(start);
      document.getElementById('portalVipEnd').textContent = admin ? 'Vô hạn' : account?.is_trial ? formatPortalDate(account?.subscription?.trial_ends_at, 'Chưa có') : `${remainingCredits} lượt · ${formatVnd(walletBalance)}`;
      document.getElementById('portalVipPercent').textContent = admin ? 'Vô hạn' : account?.is_trial ? `${percent}%` : `${remainingCredits} lượt`;
      document.getElementById('portalVipProgress').style.width = admin ? '100%' : `${percent}%`;
      document.getElementById('portalVipProgressLabel').textContent = admin ? 'Lượt dùng: Vô hạn' : account?.is_trial ? `Lượt dùng hôm nay (${used}/${limit})` : `Đã dùng ${Math.max(0, creditTotal - remainingCredits)}/${creditTotal} lượt`;
      document.getElementById('portalWalletBalance').textContent = admin ? 'Vô hạn' : formatVnd(walletBalance);
      document.getElementById('portalWalletNote').textContent = admin
        ? 'Tài khoản admin không cần nạp số dư.'
        : walletBalance > 0
          ? 'Số dư sẽ được dùng để tự gia hạn khi đủ giá gói.'
          : 'Nạp số dư để tự gia hạn gói VIP khi hết lượt.';
    }

    function isPortalRoute() {
      return location.pathname.startsWith('/portal');
    }

    function resolvePortalPage(page = 'dashboard', admin = isAdminAccount()) {
      const route = portalPageAliases[page] || portalPageAliases.dashboard;
      return admin ? route.admin : route.client;
    }

    function getRequestedPortalPage() {
      const params = new URLSearchParams(location.search);
      const queryPage = params.get('page');
      if (queryPage) return queryPage;
      return location.hash.replace(/^#/, '');
    }

    async function handlePortalRouting() {
      const requestedPage = getRequestedPortalPage();
      if (!requestedPage) {
        if (isPortalRoute()) {
          if (!currentSession) openUserModal(true);
          else await openAccountPortal(resolvePortalPage('dashboard'));
        } else {
          closeAccountPortal();
        }
        return;
      }
      if (!currentSession) {
        openUserModal(true);
        return;
      }
      const admin = isAdminAccount();
      await openAccountPortal(resolvePortalPage(requestedPage, admin));
    }

    async function openAccountPortal(page = 'userOverview') {
      if (!currentSession) {
        openUserModal(true);
        return;
      }
      closeUserModal();
      const account = currentAccount || await refreshAccount();
      renderPortalAccount(account || { user: currentSession.user, is_vip: false });
      renderPortalTables();
      renderPortalCharts();
      if (isAdminAccount(account) && page === 'userOverview') page = 'adminDashboard';
      switchPortalPage(page);
      const portal = document.getElementById('accountPortal');
      togglePortalNav(false);
      portal.classList.add('open');
      portal.setAttribute('aria-hidden', 'false');
      document.body.classList.add('portal-open');
      document.body.style.overflow = 'hidden';
      if (isPortalRoute()) {
        updatePortalUrl(page);
      } else if (!portalHistoryPushed) {
        history.pushState({ accountPortal: true }, '', location.href);
        portalHistoryPushed = true;
      }
    }

    function closeAccountPortal(fromHistory = false) {
      if (isPortalRoute() && !fromHistory) {
        window.location.href = '/tapchi/';
        return;
      }
      const portal = document.getElementById('accountPortal');
      if (!portal) return;
      togglePortalNav(false);
      if (portal.contains(document.activeElement)) document.activeElement.blur();
      portal.classList.remove('open');
      portal.setAttribute('aria-hidden', 'true');
      document.body.classList.remove('portal-open');
      document.body.style.overflow = '';
      if (location.hash) {
        history.pushState(null, '', location.pathname + location.search);
      }
      if (portalHistoryPushed && !fromHistory) {
        portalHistoryPushed = false;
        history.back();
      } else if (fromHistory) {
        portalHistoryPushed = false;
      }
    }

    window.addEventListener('popstate', () => {
      const portal = document.getElementById('accountPortal');
      if (portal?.classList.contains('open')) closeAccountPortal(true);
    });

    window.addEventListener('hashchange', handlePortalRouting);

    function togglePortalNav(force) {
      const portal = document.getElementById('accountPortal');
      if (!portal) return;
      const open = typeof force === 'boolean' ? force : !portal.classList.contains('nav-open');
      portal.classList.toggle('nav-open', open);
      const button = portal.querySelector('.portal-menu-toggle');
      if (button) {
        button.setAttribute('aria-label', open ? 'Đóng menu tài khoản' : 'Mở menu tài khoản');
        button.innerHTML = `<i class="fas fa-${open ? 'xmark' : 'bars'}"></i>`;
      }
    }

    function switchPortalPage(pageId) {
      if (pageId === 'userOverview' && isAdminAccount()) pageId = 'adminDashboard';
      if (pageId === 'userTransactions' && isAdminAccount()) pageId = 'adminInvoices';
      const page = document.getElementById(pageId);
      if (!page || (pageId.startsWith('admin') && !isAdminAccount())) return;
      document.querySelectorAll('.portal-page').forEach(item => item.classList.toggle('active', item.id === pageId));
      document.querySelectorAll('.portal-nav button[data-page]').forEach(button => button.classList.toggle('active', button.dataset.page === pageId));
      const labels = {
        userOverview: ['Chào mừng trở lại!', 'Quản lý tài khoản và theo dõi gói VIP của bạn tại đây.'],
        userTransactions: ['Lịch sử giao dịch', 'Theo dõi toàn bộ hoạt động thanh toán trên tài khoản.'],
        adminDashboard: ['Trình điều khiển', 'Dữ liệu thực từ thanh toán, tài khoản và lượt dùng AI.'],
        adminUsers: ['Quản lý người dùng', 'Theo dõi số lượng tài khoản và trạng thái VIP.'],
        adminInvoices: ['Quản lý hóa đơn', 'Theo dõi thanh toán, số lượt cộng và trạng thái giao dịch.'],
        adminSettings: ['Cài đặt hệ thống', 'Cấu hình giá VIP và số lượt sử dụng.']
      };
      const [title, subtitle] = labels[pageId] || labels.userOverview;
      document.getElementById('portalPageTitle').textContent = title;
      document.getElementById('portalPageSubtitle').textContent = subtitle;
      document.querySelector('.portal-main')?.scrollTo({ top: 0, behavior: 'smooth' });
      if (window.matchMedia('(max-width: 720px)').matches) togglePortalNav(false);
      if (pageId.startsWith('admin') && !adminDashboardData) void loadAdminDashboard();
      if (isPortalRoute()) updatePortalUrl(pageId);
    }

    function updatePortalUrl(pageId) {
      const publicPage = ({
        userOverview: 'dashboard',
        userTransactions: 'payments',
        adminDashboard: 'dashboard',
        adminInvoices: 'invoices',
        adminUsers: 'users',
        adminSettings: 'settings'
      })[pageId] || 'dashboard';
      const params = new URLSearchParams(location.search);
      params.set('page', publicPage);
      const next = `${location.pathname}?${params.toString()}`;
      const current = `${location.pathname}${location.search}${location.hash}`;
      if (next !== current) history.replaceState(history.state, '', next);
    }

    function transactionTableMarkup(rows) {
      const labels = { paid: 'Thành công', pending: 'Đang chờ', expired: 'Hết hạn', cancelled: 'Đã hủy', failed: 'Thất bại' };
      const body = rows.length ? rows.map(row => {
        const success = row.status === 'paid';
        const date = row.paid_at || row.created_at;
        const credits = Number(row.credits_granted || 0);
        const walletAmount = Number(row.wallet_amount_vnd || 0);
        const isWallet = row.order_type === 'wallet_topup';
        const detail = isWallet ? `Nạp số dư ${formatVnd(walletAmount || row.amount_vnd)}` : credits ? `${credits.toLocaleString('vi-VN')} lượt` : row.payment_code || row.plan_id || '';
        return `<tr><td data-label="Ngày">${escapeHTML(formatPortalDate(date, '-'))}</td><td data-label="Nội dung"><strong>${isWallet ? 'Nạp số dư' : 'Thanh toán VIP'}</strong><small style="display:block;color:#64748b;margin-top:3px;">${escapeHTML(detail)}</small></td><td data-label="Số tiền">${formatVnd(row.amount_vnd)}</td><td data-label="Trạng thái"><span class="portal-pill ${success ? 'green' : 'orange'}">${escapeHTML(labels[row.status] || row.status || '-')}</span></td></tr>`;
      }).join('') : '<tr><td colspan="4" style="text-align:center;color:#64748b;">Chưa có giao dịch.</td></tr>';
      return `<thead><tr><th>Ngày</th><th>Nội dung</th><th>Số tiền</th><th>Trạng thái</th></tr></thead><tbody>${body}</tbody>`;
    }

    function userTableMarkup(rows) {
      const body = rows.length ? rows.map(row => {
        const initials = String(row.name || 'U').split(' ').slice(-2).map(part => part[0]).join('').toUpperCase();
        const isAdmin = row.role === 'admin';
        const plan = isAdmin ? 'Admin' : row.is_trial ? 'Free Trial' : row.subscription?.vip_plans?.name || row.subscription?.plan_id || 'Standard';
        const active = row.is_vip || row.is_trial;
        const status = isAdmin ? 'Admin' : row.is_trial ? 'Dùng thử' : row.is_vip ? 'VIP' : 'Không hoạt động';
        const remaining = isAdmin ? 'Vô hạn' : row.is_trial ? formatPortalDate(row.subscription?.trial_ends_at, '-') : `${Number(row.subscription?.ai_credits_remaining || 0).toLocaleString('vi-VN')} lượt · ${formatVnd(row.subscription?.wallet_balance_vnd || 0)}`;
        return `<tr><td><div class="portal-user-cell"><span class="portal-mini-avatar">${escapeHTML(initials)}</span><strong>${escapeHTML(row.name || 'Người dùng')}</strong></div></td><td>${escapeHTML(row.email || '')}</td><td><span class="portal-pill">${escapeHTML(plan)}</span></td><td>${escapeHTML(remaining)}</td><td><span class="portal-pill ${active ? 'green' : 'orange'}">${status}</span></td></tr>`;
      }).join('') : '<tr><td colspan="5" style="text-align:center;color:#64748b;">Chưa có người dùng.</td></tr>';
      return `<thead><tr><th>Khách hàng</th><th>Email liên hệ</th><th>Gói dịch vụ</th><th>Lượt / Trial</th><th>Trạng thái</th></tr></thead><tbody>${body}</tbody>`;
    }

    function invoiceTableMarkup(rows) {
      const labels = { paid: 'Đã thanh toán', pending: 'Đang chờ', expired: 'Hết hạn', cancelled: 'Đã hủy', failed: 'Thất bại' };
      const body = rows.length ? rows.map(row => {
        const success = row.status === 'paid';
        const date = row.paid_at || row.created_at;
        const credits = Number(row.credits_granted || 0);
        const walletAmount = Number(row.wallet_amount_vnd || 0);
        const isWallet = row.order_type === 'wallet_topup';
        return `<tr><td data-label="Ngày">${escapeHTML(formatPortalDate(date, '-'))}</td><td data-label="Mã hóa đơn"><strong>${escapeHTML(row.payment_code || row.id || '')}</strong><small style="display:block;color:#64748b;margin-top:3px;">${escapeHTML(isWallet ? 'Nạp số dư' : row.plan_id || '')}</small></td><td data-label="Khách hàng">${escapeHTML(row.name || 'Người dùng')}<small style="display:block;color:#64748b;margin-top:3px;">${escapeHTML(row.email || '')}</small></td><td data-label="Số tiền">${formatVnd(row.amount_vnd)}</td><td data-label="Lượt / Số dư">${isWallet ? formatVnd(walletAmount || row.amount_vnd) : credits ? `${credits.toLocaleString('vi-VN')} lượt` : '-'}</td><td data-label="Trạng thái"><span class="portal-pill ${success ? 'green' : 'orange'}">${escapeHTML(labels[row.status] || row.status || '-')}</span></td></tr>`;
      }).join('') : '<tr><td colspan="6" data-label="" style="text-align:center;color:#64748b;">Chưa có hóa đơn.</td></tr>';
      return `<thead><tr><th>Ngày</th><th>Mã hóa đơn</th><th>Khách hàng</th><th>Số tiền</th><th>Lượt / Số dư</th><th>Trạng thái</th></tr></thead><tbody>${body}</tbody>`;
    }

    function renderPortalTables() {
      const accountRows = isAdminAccount() && adminDashboardData?.payments
        ? adminDashboardData.payments.slice(0, 5)
        : currentAccount?.payments || [];
      const transactionMarkup = transactionTableMarkup(accountRows);
      document.getElementById('portalTransactionTable').innerHTML = transactionMarkup;
      document.getElementById('portalTransactionFullTable').innerHTML = transactionTableMarkup(currentAccount?.payments || []);
      const users = adminDashboardData?.users || [];
      const recentInvoicesTable = document.getElementById('adminRecentInvoicesTable');
      if (recentInvoicesTable) recentInvoicesTable.innerHTML = invoiceTableMarkup((adminDashboardData?.payments || []).slice(0, 5));
      document.getElementById('adminUsersTable').innerHTML = userTableMarkup(users);
      const invoicesTable = document.getElementById('adminInvoicesTable');
      if (invoicesTable) invoicesTable.innerHTML = invoiceTableMarkup(adminDashboardData?.payments || []);
    }

    function lineChartMarkup(values, labels) {
      const width = 900;
      const height = 270;
      const pad = 28;
      const max = Math.max(...values, 1);
      const points = values.map((value, index) => {
        const x = pad + (index * (width - pad * 2)) / (values.length - 1);
        const y = height - pad - (value / max) * (height - pad * 2);
        return [x, y];
      });
      const line = points.map(point => point.join(',')).join(' ');
      const area = `${pad},${height - pad} ${line} ${width - pad},${height - pad}`;
      const grid = [0, .25, .5, .75, 1].map(step => `<line x1="${pad}" y1="${pad + step * (height - pad * 2)}" x2="${width - pad}" y2="${pad + step * (height - pad * 2)}" stroke="currentColor" opacity=".1"/>`).join('');
      const dots = points.map(([x, y]) => `<circle cx="${x}" cy="${y}" r="5" fill="#2f6df6"/>`).join('');
      const xLabels = labels.map((label, index) => `<text x="${points[index][0]}" y="${height - 3}" text-anchor="middle" fill="currentColor" opacity=".55" font-size="12">${label}</text>`).join('');
      return `<svg viewBox="0 0 ${width} ${height}" preserveAspectRatio="none" aria-label="Biểu đồ đường">${grid}<polygon points="${area}" fill="#2f6df6" opacity=".09"/><polyline points="${line}" fill="none" stroke="#2f6df6" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>${dots}${xLabels}</svg>`;
    }

    function setSegmentActive(containerId, mode) {
      document.querySelectorAll(`#${containerId} button`).forEach(button => {
        button.classList.toggle('active', button.dataset.mode === mode);
      });
    }

    function setUserChartMode(mode) {
      userChartMode = mode === 'month' ? 'month' : 'week';
      setSegmentActive('userChartFilter', userChartMode);
      renderPortalCharts();
    }

    function setAdminChartMode(mode) {
      adminChartMode = ['day', 'week', 'month'].includes(mode) ? mode : 'day';
      setSegmentActive('adminChartFilter', adminChartMode);
      renderPortalCharts();
    }

    function renderPortalCharts() {
      const usage = new Map((currentAccount?.usage_history || []).map(row => [row.usage_date, Number(row.message_count || 0)]));
      const usageDayCount = userChartMode === 'month' ? 30 : 7;
      const usageDays = Array.from({ length: usageDayCount }, (_, index) => {
        const date = new Date();
        date.setHours(0, 0, 0, 0);
        date.setDate(date.getDate() - usageDayCount + 1 + index);
        return date;
      });
      let usageValues;
      let usageLabels;
      if (userChartMode === 'month') {
        usageValues = [];
        usageLabels = [];
        for (let index = 0; index < 30; index += 5) {
          const bucket = usageDays.slice(index, index + 5);
          usageValues.push(bucket.reduce((sum, date) => sum + (usage.get(date.toISOString().slice(0, 10)) || 0), 0));
          usageLabels.push(bucket[0].toLocaleDateString('vi-VN', { day: '2-digit', month: '2-digit' }));
        }
        document.getElementById('userChartSubtitle').textContent = 'Tổng lượt sử dụng theo từng 5 ngày';
      } else {
        usageValues = usageDays.map(date => usage.get(date.toISOString().slice(0, 10)) || 0);
        usageLabels = usageDays.map(date => date.toLocaleDateString('vi-VN', { weekday: 'short' }));
        document.getElementById('userChartSubtitle').textContent = 'Theo dõi lượt sử dụng trong 7 ngày gần nhất';
      }
      document.getElementById('userUsageChart').innerHTML = lineChartMarkup(usageValues, usageLabels);

      const paid = (adminDashboardData?.payments || []).filter(row => row.status === 'paid');
      let periods = [];
      let revenueValues = [];
      if (adminChartMode === 'day') {
        periods = Array.from({ length: 7 }, (_, index) => {
          const date = new Date();
          date.setHours(0, 0, 0, 0);
          date.setDate(date.getDate() - 6 + index);
          return { start: date, end: new Date(date.getTime() + 86400000), label: date.toLocaleDateString('vi-VN', { weekday: 'short' }) };
        });
        document.getElementById('adminChartSubtitle').textContent = 'Doanh thu 7 ngày gần nhất';
      } else if (adminChartMode === 'week') {
        periods = Array.from({ length: 8 }, (_, index) => {
          const end = new Date();
          end.setHours(0, 0, 0, 0);
          end.setDate(end.getDate() - (7 - index) * 7 + 7);
          const start = new Date(end);
          start.setDate(start.getDate() - 7);
          return { start, end, label: `${start.getDate()}/${start.getMonth() + 1}` };
        });
        document.getElementById('adminChartSubtitle').textContent = 'Doanh thu 8 tuần gần nhất';
      } else {
        periods = Array.from({ length: 6 }, (_, index) => {
          const start = new Date();
          start.setHours(0, 0, 0, 0);
          start.setDate(1);
          start.setMonth(start.getMonth() - 5 + index);
          const end = new Date(start);
          end.setMonth(end.getMonth() + 1);
          return { start, end, label: `T${start.getMonth() + 1}` };
        });
        document.getElementById('adminChartSubtitle').textContent = 'Doanh thu 6 tháng gần nhất';
      }
      revenueValues = periods.map(period => paid.reduce((sum, row) => {
        const date = new Date(row.paid_at || row.created_at);
        return date >= period.start && date < period.end ? sum + Number(row.amount_vnd || 0) : sum;
      }, 0));
      document.getElementById('adminRevenueChart').innerHTML = lineChartMarkup(revenueValues, periods.map(period => period.label));
      setSegmentActive('userChartFilter', userChartMode);
      setSegmentActive('adminChartFilter', adminChartMode);
    }

    function renderAdminDashboard(data) {
      const metrics = data.metrics || {};
      document.getElementById('adminRevenueMetric').textContent = `${Number(metrics.revenue_vnd || 0).toLocaleString('vi-VN')} đ`;
      document.getElementById('adminVipMetric').textContent = Number(metrics.vip_users || 0).toLocaleString('vi-VN');
      document.getElementById('adminUsageMetric').textContent = Number(metrics.ai_uses || 0).toLocaleString('vi-VN');
      document.getElementById('adminUsersMetric').textContent = Number(metrics.total_users || 0).toLocaleString('vi-VN');
      const vipPercent = metrics.total_users ? Math.round((metrics.vip_users / metrics.total_users) * 100) : 0;
      document.getElementById('adminVipPercent').textContent = `${vipPercent}%`;
      document.getElementById('adminStandardPercent').textContent = `${100 - vipPercent}%`;
      document.getElementById('adminUserDonut').style.background = `conic-gradient(#10b981 0 ${vipPercent}%, #94a3b8 ${vipPercent}% 100%)`;

      const plan = (data.plans || []).find(item => item.id === 'chatbox_ai') || data.plans?.[0];
      if (plan) {
        document.getElementById('adminPlanPrice').value = plan.price_vnd;
        document.getElementById('adminPlanCredits').value = plan.ai_credit_amount || plan.daily_ai_limit || 30;
        document.getElementById('adminWalletUnitPrice').value = plan.price_vnd || plan.ai_wallet_unit_price_vnd || 1000;
        document.getElementById('adminTrialDays').value = plan.trial_days || 30;
        document.getElementById('adminPlanLimit').value = plan.daily_ai_limit;
        document.getElementById('adminPlanName').textContent = `${plan.name} (${plan.active ? 'đang hoạt động' : 'đã tắt'})`;
        document.getElementById('adminLimitSummary').textContent = `${plan.ai_credit_amount || plan.daily_ai_limit || 30} lượt/gói · Số dư tự gia hạn khi đủ ${formatVnd(plan.price_vnd || 0)} · Trial ${plan.daily_ai_limit} lượt/ngày trong ${plan.trial_days || 30} ngày`;
      }
      renderPortalTables();
      renderPortalCharts();
    }

    async function loadAdminDashboard() {
      if (!isAdminAccount()) return;
      try {
        adminDashboardData = await apiFetch('/api/admin/dashboard');
        renderAdminDashboard(adminDashboardData);
      } catch (error) {
        console.error('Không thể tải dashboard admin:', error.message);
      }
    }

    function scheduleAccountRealtimeRefresh(delay = 300) {
      clearTimeout(accountRealtimeTimer);
      accountRealtimeTimer = setTimeout(() => {
        if (currentSession) void refreshAccount();
      }, delay);
    }

    function scheduleAdminRealtimeRefresh(delay = 600) {
      clearTimeout(adminRealtimeTimer);
      adminRealtimeTimer = setTimeout(() => {
        if (isAdminAccount()) void loadAdminDashboard();
      }, delay);
    }

    function stopAdminRealtimeFallback() {
      if (adminRealtimeFallbackTimer) clearInterval(adminRealtimeFallbackTimer);
      adminRealtimeFallbackTimer = null;
    }

    function startAdminRealtimeFallback() {
      stopAdminRealtimeFallback();
      adminRealtimeFallbackTimer = setInterval(() => {
        if (document.hidden || !isAdminAccount()) return;
        void loadAdminDashboard();
      }, 15000);
    }

    function removeRealtimeChannel(channel) {
      if (channel) db.removeChannel(channel);
    }

    function resetRealtimeSubscriptions() {
      removeRealtimeChannel(accountRealtimeChannel);
      removeRealtimeChannel(adminRealtimeChannel);
      accountRealtimeChannel = null;
      adminRealtimeChannel = null;
      accountRealtimeUserId = null;
      clearTimeout(accountRealtimeTimer);
      clearTimeout(adminRealtimeTimer);
      stopAdminRealtimeFallback();
    }

    function syncRealtimeSubscriptions(account = currentAccount) {
      const userId = currentSession?.user?.id;
      if (!userId) {
        resetRealtimeSubscriptions();
        return;
      }

      if (!accountRealtimeChannel || accountRealtimeUserId !== userId) {
        removeRealtimeChannel(accountRealtimeChannel);
        accountRealtimeUserId = userId;
        accountRealtimeChannel = db.channel(`account-live-${userId}`)
          .on('postgres_changes', {
            event: '*',
            schema: 'public',
            table: 'payments',
            filter: `user_id=eq.${userId}`
          }, payload => {
            if (payload.new?.payment_code === activePaymentCode && payload.new?.status === 'paid') {
              void finishPaidPayment();
              return;
            }
            scheduleAccountRealtimeRefresh();
          })
          .on('postgres_changes', {
            event: '*',
            schema: 'public',
            table: 'subscriptions',
            filter: `user_id=eq.${userId}`
          }, () => scheduleAccountRealtimeRefresh())
          .on('postgres_changes', {
            event: '*',
            schema: 'public',
            table: 'ai_usage',
            filter: `user_id=eq.${userId}`
          }, () => scheduleAccountRealtimeRefresh(700))
          .subscribe(status => {
            if (status === 'CHANNEL_ERROR') scheduleAccountRealtimeRefresh(1500);
          });
      }

      if (account?.role === 'admin') {
        if (!adminRealtimeChannel) {
          adminRealtimeChannel = db.channel('admin-live-dashboard')
            .on('postgres_changes', { event: '*', schema: 'public', table: 'payments' }, () => scheduleAdminRealtimeRefresh())
            .on('postgres_changes', { event: '*', schema: 'public', table: 'subscriptions' }, () => scheduleAdminRealtimeRefresh())
            .on('postgres_changes', { event: '*', schema: 'public', table: 'profiles' }, () => scheduleAdminRealtimeRefresh())
            .subscribe(status => {
              if (status === 'CHANNEL_ERROR') scheduleAdminRealtimeRefresh(1500);
            });
        }
        if (!adminRealtimeFallbackTimer) startAdminRealtimeFallback();
      } else {
        removeRealtimeChannel(adminRealtimeChannel);
        adminRealtimeChannel = null;
        stopAdminRealtimeFallback();
      }
    }

    async function saveAdminSettings() {
      const message = document.getElementById('adminSettingsMessage');
      try {
        const plan = (adminDashboardData?.plans || []).find(item => item.id === 'chatbox_ai') || adminDashboardData?.plans?.[0];
        const result = await apiFetch('/api/admin/settings', {
          method: 'PATCH',
          body: JSON.stringify({
            id: plan?.id || 'chatbox_ai',
            price_vnd: Number(document.getElementById('adminPlanPrice').value),
            ai_credit_amount: Number(document.getElementById('adminPlanCredits').value),
            ai_wallet_unit_price_vnd: Number(document.getElementById('adminPlanPrice').value),
            trial_days: Number(document.getElementById('adminTrialDays').value),
            daily_ai_limit: Number(document.getElementById('adminPlanLimit').value)
          })
        });
        const index = adminDashboardData.plans.findIndex(item => item.id === result.plan.id);
        if (index >= 0) adminDashboardData.plans[index] = result.plan;
        renderAdminDashboard(adminDashboardData);
        message.textContent = `Đã lưu cấu hình và đồng bộ ${Number(result.synced_trials || 0)} tài khoản trial.`;
        message.className = 'vip-message success';
      } catch (error) {
        message.textContent = error.message || 'Không thể lưu cấu hình.';
        message.className = 'vip-message error';
      }
    }

    // ─── Tiện ích Excel ───────────────────────────────────────────────
    function _xlsxStyleHeader(ws, headers) {
      if (typeof XLSX === 'undefined') return;
      headers.forEach((_, colIdx) => {
        const cellRef = XLSX.utils.encode_cell({ r: 0, c: colIdx });
        if (!ws[cellRef]) return;
        ws[cellRef].s = {
          font: { bold: true, color: { rgb: 'FFFFFF' } },
          fill: { fgColor: { rgb: '1E3A5F' } },
          alignment: { horizontal: 'center', vertical: 'center', wrapText: true },
          border: { bottom: { style: 'thin', color: { rgb: '94A3B8' } } }
        };
      });
    }

    function _downloadXlsx(wb, filename) {
      if (typeof XLSX === 'undefined') { alert('Thư viện xuất Excel chưa tải xong, vui lòng thử lại.'); return; }
      XLSX.writeFile(wb, filename, { bookType: 'xlsx', type: 'binary', cellStyles: true });
    }

    // ─── Xuất danh sách người dùng → Excel ───────────────────────────
    function exportAdminUsers() {
      if (typeof XLSX === 'undefined') { alert('Thư viện xuất Excel chưa tải xong, vui lòng thử lại.'); return; }
      const users = adminDashboardData?.users || [];
      const headers = ['Tên', 'Email', 'Vai trò', 'VIP', 'Lượt còn lại', 'Số dư (VND)', 'Trial đến'];
      const rows = users.map(u => ([
        u.name || '',
        u.email || '',
        u.role || 'user',
        u.is_vip ? 'Có' : 'Không',
        Number(u.subscription?.ai_credits_remaining || 0),
        Number(u.subscription?.wallet_balance_vnd || 0),
        formatPortalDate(u.subscription?.trial_ends_at, '')
      ]));
      const ws = XLSX.utils.aoa_to_sheet([headers, ...rows]);
      ws['!cols'] = [{ wch: 24 }, { wch: 32 }, { wch: 10 }, { wch: 6 }, { wch: 12 }, { wch: 14 }, { wch: 18 }];
      _xlsxStyleHeader(ws, headers);
      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, ws, 'Người dùng');
      _downloadXlsx(wb, `nguoi-dung-${new Date().toISOString().slice(0, 10)}.xlsx`);
    }

    // ─── Xuất hóa đơn → Excel ────────────────────────────────────────
    function exportAdminInvoices() {
      if (typeof XLSX === 'undefined') { alert('Thư viện xuất Excel chưa tải xong, vui lòng thử lại.'); return; }
      const rows = adminDashboardData?.payments || [];
      const headers = ['Ngày', 'Mã hóa đơn', 'Khách hàng', 'Email', 'Loại', 'Gói', 'Số tiền (VND)', 'Lượt cộng', 'Số dư nạp (VND)', 'Trạng thái'];
      const data = rows.map(r => ([
        formatPortalDate(r.paid_at || r.created_at, ''),
        r.payment_code || r.id || '',
        r.name || '',
        r.email || '',
        r.order_type === 'wallet_topup' ? 'Nạp số dư' : 'Mua lượt VIP',
        r.plan_id || '',
        Number(r.amount_vnd || 0),
        Number(r.credits_granted || 0),
        Number(r.wallet_amount_vnd || 0),
        r.status || ''
      ]));
      const ws = XLSX.utils.aoa_to_sheet([headers, ...data]);
      ws['!cols'] = [{ wch: 18 }, { wch: 20 }, { wch: 22 }, { wch: 30 }, { wch: 14 }, { wch: 16 }, { wch: 16 }, { wch: 12 }, { wch: 16 }, { wch: 12 }];
      _xlsxStyleHeader(ws, headers);
      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, ws, 'Hóa đơn');
      _downloadXlsx(wb, `hoa-don-${new Date().toISOString().slice(0, 10)}.xlsx`);
    }

    // ─── Xuất hóa đơn → PDF ─────────────────────────────────────────
    // ─── Bỏ dấu tiếng Việt → ASCII (dùng cho jsPDF vì Helvetica không hỗ trợ Unicode)
    function normalizePdfText(str) {
      if (!str) return '';
      // Các ký tự cơ bản tiếng Việt không decompose qua NFD
      const map = {
        'ơ':'o','Ơ':'O','ư':'u','Ư':'U','đ':'d','Đ':'D',
        'ă':'a','Ă':'A','â':'a','Â':'A','ê':'e','Ê':'E',
        'ô':'o','Ô':'O'
      };
      str = str.replace(/[ơƠưƯđĐăĂâÂêÊôÔ]/g, c => map[c] ?? c);
      // Bỏ các combining diacritical marks còn lại (hỏi/ngã/sắc/huyền/nặng)
      return str.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
    }

    function fmtVndPdf(n) {
      // Dùng dấu chấm thập phân để tương thích font Latin (tránh lỗi ký tự '.')
      return Number(n || 0).toLocaleString('en-US') + ' VND';
    }

    function exportAdminInvoicesPDF() {
      if (typeof window.jspdf === 'undefined') { alert('Thư viện xuất PDF chưa tải xong, vui lòng thử lại.'); return; }
      const { jsPDF } = window.jspdf;
      const rows = adminDashboardData?.payments || [];
      if (!rows.length) { alert('Không có hóa đơn để xuất.'); return; }
      const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
      const pageW = doc.internal.pageSize.getWidth();
      const today = new Date();
      const dateStr = `${today.getDate()}/${today.getMonth() + 1}/${today.getFullYear()}`;

      // Tiêu đề (toàn ASCII — an toàn với Helvetica)
      doc.setFillColor(30, 58, 95);
      doc.rect(0, 0, pageW, 22, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(15);
      doc.setFont('helvetica', 'bold');
      doc.text('DANH SACH HOA DON THANH TOAN', pageW / 2, 10, { align: 'center' });
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.text(`Xuat ngay: ${dateStr}  |  Tong so: ${rows.length} giao dich`, pageW / 2, 17, { align: 'center' });

      // Cột và header
      const colW = [24, 32, 34, 42, 22, 20, 28, 14, 26, 16];
      const headers = ['Ngay', 'Ma HD', 'Khach hang', 'Email', 'Loai', 'Goi', 'So tien', 'Luot', 'So du nap', 'TT'];
      let y = 28;

      const drawRow = (cells, rowY, isBold, bgRgb) => {
        let x = 6;
        if (bgRgb) {
          doc.setFillColor(...bgRgb);
          doc.rect(x - 1, rowY - 4.5, pageW - 10, 7.5, 'F');
        }
        doc.setFont('helvetica', isBold ? 'bold' : 'normal');
        doc.setTextColor(isBold ? 255 : 25, isBold ? 255 : 35, isBold ? 255 : 55);
        doc.setFontSize(7.5);
        cells.forEach((cell, i) => {
          // Giới hạn độ dài + bỏ dấu để font hiển thị đúng
          const raw = normalizePdfText(String(cell ?? ''));
          const maxChars = Math.floor(colW[i] / 1.85);
          const txt = raw.length > maxChars ? raw.substring(0, maxChars - 1) + '.' : raw;
          doc.text(txt, x + 1, rowY);
          x += colW[i];
        });
      };

      drawRow(headers, y, true, [30, 58, 95]);
      y += 8.5;

      rows.forEach((r, idx) => {
        if (y > 188) {
          doc.addPage();
          y = 14;
          drawRow(headers, y, true, [30, 58, 95]);
          y += 8.5;
        }
        const bg = idx % 2 === 0 ? [238, 244, 255] : [250, 252, 255];
        const cells = [
          formatPortalDate(r.paid_at || r.created_at, ''),
          (r.payment_code || r.id || '').substring(0, 16),
          r.name || '',
          r.email || '',
          r.order_type === 'wallet_topup' ? 'Nap so du' : 'Mua luot VIP',
          r.plan_id || '',
          fmtVndPdf(r.amount_vnd),
          String(r.credits_granted || 0),
          fmtVndPdf(r.wallet_amount_vnd),
          r.status || ''
        ];
        drawRow(cells, y, false, bg);
        y += 7.5;
      });

      // Đường kẻ cuối + tổng kết
      doc.setDrawColor(180, 190, 210);
      doc.line(6, y + 1, pageW - 6, y + 1);
      doc.setTextColor(80, 95, 120);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      const totalRevenue = rows.filter(r => r.status === 'paid').reduce((s, r) => s + Number(r.amount_vnd || 0), 0);
      doc.text(`Tong doanh thu (paid): ${fmtVndPdf(totalRevenue)}`, 6, y + 7);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(140, 150, 165);
      doc.setFontSize(7);
      doc.text('Bao cao duoc xuat tu He thong Tra cuu Tap chi', pageW - 6, y + 7, { align: 'right' });

      doc.save(`hoa-don-${new Date().toISOString().slice(0, 10)}.pdf`);
    }

    // ─── Xuất báo cáo tổng hợp → Excel ──────────────────────────────
    function exportAdminSummary() {
      if (typeof XLSX === 'undefined') { alert('Thư viện xuất Excel chưa tải xong, vui lòng thử lại.'); return; }
      const payments = adminDashboardData?.payments || [];
      const metrics = adminDashboardData?.metrics || {};
      const users = adminDashboardData?.users || [];
      const wb = XLSX.utils.book_new();

      // Sheet 1: Tổng quan
      const overviewHeaders = ['Chỉ số', 'Giá trị'];
      const overviewData = [
        ['Tổng doanh thu (VND)', Number(metrics.revenue_vnd || 0)],
        ['Số người dùng VIP', Number(metrics.vip_users || 0)],
        ['Tổng tài khoản', Number(metrics.total_users || 0)],
        ['Tổng lượt dùng AI', Number(metrics.ai_uses || 0)],
        ['Ngày xuất báo cáo', new Date().toLocaleDateString('vi-VN')]
      ];
      const ws1 = XLSX.utils.aoa_to_sheet([overviewHeaders, ...overviewData]);
      ws1['!cols'] = [{ wch: 28 }, { wch: 20 }];
      _xlsxStyleHeader(ws1, overviewHeaders);
      XLSX.utils.book_append_sheet(wb, ws1, 'Tổng quan');

      // Sheet 2: Doanh thu theo tháng
      const byMonth = {};
      payments.forEach(p => {
        if (p.status !== 'paid') return;
        const d = new Date(p.paid_at || p.created_at);
        const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
        if (!byMonth[key]) byMonth[key] = { month: key, count: 0, revenue: 0, credits: 0, wallet: 0 };
        byMonth[key].count++;
        byMonth[key].revenue += Number(p.amount_vnd || 0);
        byMonth[key].credits += Number(p.credits_granted || 0);
        byMonth[key].wallet += Number(p.wallet_amount_vnd || 0);
      });
      const monthHeaders = ['Tháng', 'Số giao dịch', 'Doanh thu (VND)', 'Lượt VIP cộng', 'Số dư nạp (VND)'];
      const monthRows = Object.values(byMonth).sort((a, b) => a.month.localeCompare(b.month))
        .map(m => [m.month, m.count, m.revenue, m.credits, m.wallet]);
      const ws2 = XLSX.utils.aoa_to_sheet([monthHeaders, ...monthRows]);
      ws2['!cols'] = [{ wch: 12 }, { wch: 16 }, { wch: 18 }, { wch: 16 }, { wch: 18 }];
      _xlsxStyleHeader(ws2, monthHeaders);
      XLSX.utils.book_append_sheet(wb, ws2, 'Doanh thu theo tháng');

      // Sheet 3: Hóa đơn đầy đủ
      const invHeaders = ['Ngày', 'Mã hóa đơn', 'Khách hàng', 'Email', 'Loại', 'Gói', 'Số tiền (VND)', 'Lượt cộng', 'Số dư nạp (VND)', 'Trạng thái'];
      const invRows = payments.map(r => ([
        formatPortalDate(r.paid_at || r.created_at, ''),
        r.payment_code || r.id || '',
        r.name || '',
        r.email || '',
        r.order_type === 'wallet_topup' ? 'Nạp số dư' : 'Mua lượt VIP',
        r.plan_id || '',
        Number(r.amount_vnd || 0),
        Number(r.credits_granted || 0),
        Number(r.wallet_amount_vnd || 0),
        r.status || ''
      ]));
      const ws3 = XLSX.utils.aoa_to_sheet([invHeaders, ...invRows]);
      ws3['!cols'] = [{ wch: 18 }, { wch: 20 }, { wch: 22 }, { wch: 30 }, { wch: 14 }, { wch: 16 }, { wch: 16 }, { wch: 12 }, { wch: 16 }, { wch: 12 }];
      _xlsxStyleHeader(ws3, invHeaders);
      XLSX.utils.book_append_sheet(wb, ws3, 'Hóa đơn');

      // Sheet 4: Người dùng
      const userHeaders = ['Tên', 'Email', 'Vai trò', 'VIP', 'Lượt còn lại', 'Số dư (VND)', 'Trial đến'];
      const userRows = users.map(u => ([
        u.name || '',
        u.email || '',
        u.role || 'user',
        u.is_vip ? 'Có' : 'Không',
        Number(u.subscription?.ai_credits_remaining || 0),
        Number(u.subscription?.wallet_balance_vnd || 0),
        formatPortalDate(u.subscription?.trial_ends_at, '')
      ]));
      const ws4 = XLSX.utils.aoa_to_sheet([userHeaders, ...userRows]);
      ws4['!cols'] = [{ wch: 24 }, { wch: 32 }, { wch: 10 }, { wch: 6 }, { wch: 12 }, { wch: 14 }, { wch: 18 }];
      _xlsxStyleHeader(ws4, userHeaders);
      XLSX.utils.book_append_sheet(wb, ws4, 'Người dùng');

      _downloadXlsx(wb, `bao-cao-tong-hop-${new Date().toISOString().slice(0, 10)}.xlsx`);
    }

    async function changePortalPassword(event) {
      event.preventDefault();
      const form = event.currentTarget;
      const passwordFields = [...form.querySelectorAll('input[type="password"]')];
      const nextPassword = passwordFields[passwordFields.length - 2]?.value || '';
      const confirmPassword = passwordFields[passwordFields.length - 1]?.value || '';
      const message = form.querySelector('.vip-message') || document.getElementById('portalPasswordMessage');
      if (nextPassword !== confirmPassword) {
        if (message) {
          message.textContent = 'Mật khẩu xác nhận chưa khớp.';
          message.className = 'vip-message error';
        }
        return;
      }
      const { error } = await auth.updatePassword(nextPassword);
      if (message) {
        message.textContent = error ? error.message : 'Đã cập nhật mật khẩu.';
        message.className = `vip-message ${error ? 'error' : 'success'}`;
      }
      if (!error) form.reset();
    }

    async function refreshAccount() {
      if (!currentSession) return null;
      if (accountRefreshPromise) return accountRefreshPromise;

      accountRefreshPromise = (async () => {
        try {
          currentAccount = await apiFetch('/api/account');
          renderAccount(currentAccount);
          syncRealtimeSubscriptions(currentAccount);
          const portal = document.getElementById('accountPortal');
          if (portal?.classList.contains('open')) {
            renderPortalTables();
            renderPortalCharts();
            if (isAdminAccount(currentAccount)) {
              const activePage = document.querySelector('.portal-page.active')?.id;
              if (!activePage || activePage === 'userOverview') switchPortalPage('adminDashboard');
              void loadAdminDashboard();
            }
          }
          return currentAccount;
        } catch (error) {
          if (error.status !== 401) setUserMessage(error.message, 'error');
          return null;
        } finally {
          accountRefreshPromise = null;
        }
      })();

      return accountRefreshPromise;
    }

    function updateAuthUi() {
      const button = document.getElementById('accountButton');
      if (currentSession?.user) {
        if (button) button.innerHTML = '<i class="fas fa-user-check"></i> Tài khoản';
      } else {
        if (button) button.innerHTML = '<i class="fas fa-user"></i> Đăng nhập';
        const chatAccessNote = document.getElementById('chat-access-note');
        if (chatAccessNote) chatAccessNote.style.display = 'block';
      }
      const recovering = passwordRecoveryActive || passwordRecoveryRequested;
      const authView = document.getElementById('authView');
      const accountView = document.getElementById('accountView');
      if (authView) authView.style.display = recovering || !currentSession ? 'block' : 'none';
      if (accountView) accountView.style.display = currentSession && !recovering ? 'block' : 'none';
    }

    async function initAuth() {
      currentSession = await auth.getSession();
      updateAuthUi();
      passwordRecoveryRequested = passwordRecoveryRequested
        || new URL(location.href).searchParams.get('recovery') === '1'
        || new URL(location.href).searchParams.get('type') === 'recovery'
        || new URLSearchParams(location.hash.slice(1)).get('type') === 'recovery';
      if (currentSession && passwordRecoveryRequested) {
        showPasswordRecovery();
      } else if (currentSession) {
        await refreshAccount();
        await handlePortalRouting();
      } else if (passwordRecoveryRequested) {
        if (hasLocalAuthForm()) {
          openUserModal(true);
          setAuthMode('login');
          setUserMessage('Liên kết đặt lại mật khẩu không hợp lệ hoặc đã hết hạn. Hãy yêu cầu liên kết mới.', 'error');
        } else {
          redirectToSharedAuth('reset');
        }
      } else if (isPortalRoute()) {
        redirectToSharedAuth('login');
      }
      auth.onAuthStateChange((event, session) => {
        currentSession = session;
        if (event === 'SIGNED_OUT' || event === 'USER_DELETED') {
          currentAccount = null;
          resetRealtimeSubscriptions();
        }
        setTimeout(async () => {
          updateAuthUi();
          if (event === 'PASSWORD_RECOVERY') {
            showPasswordRecovery();
          } else if (event === 'SIGNED_IN' && session && !passwordRecoveryActive && !passwordRecoveryRequested) {
            currentAccount = null;
            await refreshAccount();
            const authView = document.getElementById('authView');
            const accountView = document.getElementById('accountView');
            if (authView) authView.style.display = 'none';
            if (accountView) accountView.style.display = 'block';
            await handlePortalRouting();
          }
        }, 0);
      });
    }

    function stopPaymentPolling() {
      if (paymentPollTimer) clearTimeout(paymentPollTimer);
      paymentPollTimer = null;
    }

    async function finishPaidPayment() {
      activePaymentCode = null;
      stopPaymentPolling();
      document.getElementById('paymentBox').classList.remove('open');
      document.getElementById('paymentQr').removeAttribute('src');
      setUserMessage('Thanh toán thành công! VIP đã được kích hoạt.', 'success');
      await refreshAccount();
      renderPortalTables();
      renderPortalCharts();
      if (isAdminAccount()) void loadAdminDashboard();
      closeUserModal();
    }

    async function pollPayment(code, expiresAt) {
      stopPaymentPolling();
      const countdown = document.getElementById('paymentCountdown');
      const tick = async () => {
        const remaining = new Date(expiresAt).getTime() - Date.now();
        if (remaining <= 0) {
          countdown.textContent = 'Đơn thanh toán đã hết hạn.';
          countdown.className = 'vip-message error';
          return;
        }
        const minutes = String(Math.floor(remaining / 60000)).padStart(2, '0');
        const seconds = String(Math.floor((remaining % 60000) / 1000)).padStart(2, '0');
        countdown.textContent = `Đang chờ thanh toán · ${minutes}:${seconds}`;
        try {
          const order = await apiFetch(`/api/orders/${encodeURIComponent(code)}/status`);
          if (order.status === 'paid') {
            await finishPaidPayment();
            return;
          }
        } catch (_) { }
        paymentPollTimer = setTimeout(tick, 4000);
      };
      tick();
    }

    async function createPaymentOrder(orderType = 'vip_credits', amountVnd = 0) {
      setUserMessage(orderType === 'wallet_topup' ? 'Đang tạo mã nạp số dư...' : 'Đang tạo mã thanh toán...');
      try {
        const order = await apiFetch('/api/orders', {
          method: 'POST',
          body: JSON.stringify({
            order_type: orderType,
            ...(orderType === 'wallet_topup' ? { amount_vnd: amountVnd } : {})
          })
        });
        activePaymentCode = order.code;
        currentAccount = currentAccount || { user: currentSession?.user, payments: [] };
        currentAccount.payments = currentAccount.payments || [];
        if (!currentAccount.payments.some(payment => payment.payment_code === order.code)) {
          currentAccount.payments.unshift({
            id: order.id,
            payment_code: order.code,
            amount_vnd: order.amount,
            status: order.status || 'pending',
            order_type: order.order_type || orderType,
            created_at: new Date().toISOString(),
            expires_at: order.expires_at
          });
        }
        renderPortalTables();
        document.getElementById('paymentQr').src = order.qr_url;
        document.getElementById('paymentCode').textContent = order.code;
        document.getElementById('paymentAmount').textContent = new Intl.NumberFormat('vi-VN', {
          style: 'currency', currency: 'VND'
        }).format(order.amount);
        document.getElementById('paymentBox').classList.add('open');
        setUserMessage('Quét QR và giữ nguyên nội dung chuyển khoản.', 'success');
        pollPayment(order.code, order.expires_at);
      } catch (error) {
        setUserMessage(error.message, 'error');
      }
    }

    async function createVipOrder() {
      await createPaymentOrder('vip_credits');
    }

    function createWalletTopupOrder() {
      openWalletTopupModal();
    }

    function openWalletTopupModal() {
      const modal = document.getElementById('walletTopupModal');
      const input = document.getElementById('walletTopupAmount');
      const message = document.getElementById('walletTopupMessage');
      if (message) {
        message.textContent = '';
        message.className = 'vip-message';
      }
      modal.classList.add('open');
      setTimeout(() => input?.focus(), 50);
    }

    function closeWalletTopupModal() {
      document.getElementById('walletTopupModal')?.classList.remove('open');
    }

    function setWalletTopupAmount(amount) {
      const input = document.getElementById('walletTopupAmount');
      if (input) input.value = amount;
    }

    async function submitWalletTopup(event) {
      event.preventDefault();
      const input = document.getElementById('walletTopupAmount');
      const message = document.getElementById('walletTopupMessage');
      const amount = Number(input?.value || 0);
      if (!Number.isSafeInteger(amount) || amount < 1000) {
        if (message) {
          message.textContent = 'Số tiền nạp tối thiểu là 1.000đ.';
          message.className = 'vip-message error';
        }
        return;
      }
      closeWalletTopupModal();
      await createPaymentOrder('wallet_topup', amount);
    }
export const accountState = {
  get currentSession() { return currentSession },
  set currentSession(value) { currentSession = value },
  get currentAccount() { return currentAccount },
  set currentAccount(value) { currentAccount = value }
}

export {
  apiFetch,
  loadPublicConfig,
  setAuthMode,
  showPasswordRecovery,
  togglePasswordVisibility,
  openUserModal,
  closeUserModal,
  submitAuth,
  requestPasswordReset,
  updatePasswordRules,
  saveNewPassword,
  signOutUser,
  renderAccount,
  isAdminAccount,
  openAccountPortal,
  closeAccountPortal,
  togglePortalNav,
  switchPortalPage,
  setUserChartMode,
  setAdminChartMode,
  loadAdminDashboard,
  saveAdminSettings,
  exportAdminUsers,
  exportAdminInvoices,
  exportAdminInvoicesPDF,
  exportAdminSummary,
  changePortalPassword,
  refreshAccount,
  initAuth,
  createVipOrder,
  createWalletTopupOrder,
  openWalletTopupModal,
  closeWalletTopupModal,
  setWalletTopupAmount,
  submitWalletTopup
}

export function initAccountEvents() {
  const on = (selector, event, handler) => document.querySelector(selector)?.addEventListener(event, handler)

  on('#accountButton', 'click', () => openUserModal())
  on('#userModal', 'click', event => { if (event.target === event.currentTarget) closeUserModal() })
  on('#loginTab', 'click', () => setAuthMode('login'))
  on('#registerTab', 'click', () => setAuthMode('register'))
  on('#passwordResetRequest', 'click', requestPasswordReset)
  on('#authForm', 'submit', submitAuth)
  on('#resetView', 'submit', saveNewPassword)
  on('#walletTopupForm', 'submit', submitWalletTopup)
  document.querySelectorAll('[data-action="change-portal-password"]').forEach(form => form.addEventListener('submit', changePortalPassword))
  on('#authPasswordToggle', 'click', event => togglePasswordVisibility('authPassword', event.currentTarget))
  on('#newPassword', 'input', event => updatePasswordRules(event.currentTarget.value))
  on('#newPasswordToggle', 'click', event => togglePasswordVisibility('newPassword', event.currentTarget))
  on('#confirmNewPasswordToggle', 'click', event => togglePasswordVisibility('confirmNewPassword', event.currentTarget))

  document.querySelectorAll('[data-action="close-user-modal"]').forEach(button => button.addEventListener('click', closeUserModal))
  document.querySelectorAll('[data-action="create-vip-order"]').forEach(button => button.addEventListener('click', createVipOrder))
  document.querySelectorAll('[data-action="create-vip-order-and-open"]').forEach(button => button.addEventListener('click', async () => { await createVipOrder(); openUserModal(true) }))
  document.querySelectorAll('[data-action="create-wallet-topup-order"]').forEach(button => button.addEventListener('click', createWalletTopupOrder))
  document.querySelectorAll('[data-action="create-wallet-topup-order-and-open"]').forEach(button => button.addEventListener('click', () => { createWalletTopupOrder(); openUserModal(true) }))
  document.querySelectorAll('[data-action="sign-out"]').forEach(button => button.addEventListener('click', signOutUser))

  on('#walletTopupModal', 'click', event => { if (event.target === event.currentTarget) closeWalletTopupModal() })
  document.querySelectorAll('[data-action="close-wallet-topup-modal"]').forEach(button => button.addEventListener('click', closeWalletTopupModal))
  document.querySelectorAll('[data-action="close-account-portal"]').forEach(button => button.addEventListener('click', closeAccountPortal))
  document.querySelectorAll('[data-wallet-amount]').forEach(button => {
    button.addEventListener('click', () => setWalletTopupAmount(Number(button.dataset.walletAmount || 0)))
  })

  on('.portal-nav-backdrop', 'click', () => togglePortalNav(false))
  on('.portal-menu-toggle', 'click', () => togglePortalNav())
  document.querySelectorAll('[data-portal-page]').forEach(button => {
    button.addEventListener('click', () => switchPortalPage(button.dataset.portalPage))
  })
  document.querySelectorAll('[data-user-chart-mode]').forEach(button => {
    button.addEventListener('click', () => setUserChartMode(button.dataset.userChartMode))
  })
  document.querySelectorAll('[data-admin-chart-mode]').forEach(button => {
    button.addEventListener('click', () => setAdminChartMode(button.dataset.adminChartMode))
  })
  on('[data-action="portal-smart-transactions"]', 'click', () => switchPortalPage(isAdminAccount() ? 'adminInvoices' : 'userTransactions'))
  on('[data-action="export-admin-summary"]', 'click', exportAdminSummary)
  on('[data-action="export-admin-users"]', 'click', exportAdminUsers)
  on('[data-action="export-admin-invoices"]', 'click', exportAdminInvoices)
  on('[data-action="export-admin-invoices-pdf"]', 'click', exportAdminInvoicesPDF)
  on('[data-action="save-admin-settings"]', 'click', saveAdminSettings)
}
